In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from sklearn.datasets import make_classification

In [5]:
X,Y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [6]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]])

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train,Y_train)
Y_pred=logistic.predict(X_test)
print(Y_pred)

[2 0 1 2 0 1 2 0 0 2 2 2 2 2 2 2 2 1 0 0 0 0 2 0 1 0 2 1 0 2 2 0 1 0 0 2 2
 2 1 0 0 1 2 0 1 2 1 0 1 1 2 0 1 0 2 2 2 2 1 2 0 2 2 2 1 1 0 1 0 1 0 2 2 0
 0 0 2 1 1 2 2 0 2 1 0 1 1 2 1 1 2 2 1 2 2 2 1 0 0 0 0 2 1 0 2 1 1 0 0 2 0
 1 2 0 0 0 1 1 2 2 1 0 0 1 2 0 0 1 0 2 1 0 2 2 2 0 0 1 2 1 2 1 2 1 2 2 2 0
 0 1 2 0 0 2 1 0 0 0 2 0 0 0 2 2 2 2 2 1 2 1 0 2 1 0 0 2 0 1 1 2 2 0 0 2 0
 0 0 2 0 0 0 0 2 1 2 2 1 2 0 1 2 2 1 1 0 2 1 2 2 2 2 2 0 0 0 0 0 0 1 0 1 2
 2 2 0 0 0 0 0 2 2 0 0 2 2 1 0 1 2 0 0 2 0 2 0 0 2 2 0 2 2 0 1 2 2 0 1 1 0
 1 2 0 2 2 0 0 0 2 1 2 0 2 2 2 0 2 0 2 2 0 0 1 0 2 2 2 0 2 2 0 2 2 0 2 0 0
 2 2 0 1]


e:\MACHINE LEARNING\env\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(Y_test,Y_pred)
print(score)
cm=confusion_matrix(Y_test,Y_pred)
print(cm)
print(classification_report(Y_test,Y_pred))

0.68
[[79 16  8]
 [31 38 27]
 [ 3 11 87]]
              precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300

